server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_3d
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect


  profiles:
    active: test


